# Generated by Django 5.0.7 on 2024-07-21 11:24

from django.db import migrations, models
import uuid
import random
import string


def create_fake_data(apps, schema_editor):
    # Get the models
    Category = apps.get_model('advert', 'Category')
    City = apps.get_model('advert', 'City')
    Advert = apps.get_model('advert', 'Advert')

    # Get the database connection
    connection = schema_editor.connection

    # Create fake cities
    fake_cities = []
    for _ in range(10):
        fake_cities.append(City(name=''.join(random.choices(string.ascii_letters, k=10))))
    City.objects.bulk_create(fake_cities)

    # Create fake categories
    fake_categories = []
    for _ in range(10):
        fake_categories.append(Category(name=''.join(random.choices(string.ascii_letters, k=10))))
    Category.objects.bulk_create(fake_categories)

    # Get all city and category ids
    city_ids = list(City.objects.values_list('uuid', flat=True))
    category_ids = list(Category.objects.values_list('uuid', flat=True))

    # Create fake adverts
    fake_adverts = []
    for _ in range(2000000):
        fake_adverts.append(Advert(title=''.join(random.choices(string.ascii_letters, k=10)),
            description=''.join(random.choices(string.ascii_letters, k=50)), views=random.randint(0, 1000),
            category_id=random.choice(category_ids), city_id=random.choice(city_ids)))
        if len(fake_adverts) % 10000 == 0:
            Advert.objects.bulk_create(fake_adverts)
            fake_adverts = []

    # Insert any remaining adverts
    if fake_adverts:
        Advert.objects.bulk_create(fake_adverts)


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0001_initial'),
    ]

    operations = [migrations.RunPython(create_fake_data),]
