version: '3.7'

services:
  db:
    image: postgres:15.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 30s
      retries: 15

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - .:/app
    ports:
      - "8002:8002"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DB_NAME=testdb
      - DB_USER=test_u
      - DB_PASSWORD=test
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  postgres_data:
